version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: "python manage.py runserver -h 0.0.0.0 -p 5000"  
    volumes:
      - .:/sample_microservice
    ports:
      - "5000:5000"
    image: web:sample_microservice
    container_name: sample_microservice
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - SM_VERSION=1.0
      - SM_SECRET_KEY=40d9e42d-c46e-5732-88f0-ef7d85f7a1bd
      - SM_ENABLE_LOGGING=False
